language: python
notifications:
  email: true
python:
  - "2.6"
  - "2.7"
install:
  - "sudo apt-get install freetds-dev python-numpy python-matplotlib python-scipy python-pymssql -qq -y"
  - "easy_install -U setuptools"
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
script:
  - py.test test/test_smash.py --doctest-modules -v --cov smash --cov-report term-missing
after_success:
  - coveralls